urls.py
from django.shortcuts import render_to_response
from django.conf.urls.defaults import *
from django.contrib.auth.views import login,logout,logout_then_login,password_reset,password_reset_done,password_reset_complete,password_reset_confirm
from django.conf import settings
from itrack.system.forms import UserCompleteForm, SettingsForm, SystemForm, SystemWizard

from django.contrib.gis import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

urlpatterns = patterns('',
url(r'^$', 'main.views.index'),
url(r'^accounts/login/$', 'accounts.views.login' ),
url(r'^accounts/logout/$', logout_then_login),
url(r'^accounts/$', 'accounts.views.index'),
url(r'^accounts/password/reset/$', password_reset, {'template_name': 'accounts/templates/password_reset_form.html','email_template_name': 'accounts/templates/password_reset_email.html','post_reset_redirect' : '/accounts/password/reset/done/'}),
url(r'^accounts/password/reset/done/$', password_reset_done, {'template_name': 'accounts/templates/password_reset_done.html'}),
url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/templates/password_reset_confirm.html','post_reset_redirect' : '/accounts/password/done/'}), 
url(r'^accounts/password/done/$',password_reset_complete, {'template_name': 'accounts/templates/password_reset_complete.html'}),

url(r'^admin/', include(admin.site.urls)),
url(r'^media/(.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),
url(r'^accounts/profile/$', 'main.views.index'),
url(r'^themes/$', 'themes.views.index'),

url(r'^images/(.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),

url(r'^system/$','system.views.index'),
url(r'^system/create/$','system.views.create'),
url(r'^system/edit/(\d+)/$','system.views.edit'),
url(r'^system/delete/(\d+)/$','system.views.delete'),
url(r'^system/finish/$','system.views.finish'),
url(r'^system/edit/finish/$','system.views.editfinish'),
url(r'^system/delete/finish/$','system.views.deletefinish'),
url(r'^sys_not_created/$','system.views.sys_not_created'),
url(r'^system/sms_count/$','system.ajax.get_sms_count'),


url(r'^equipment/$','equipments.views.index'),
url(r'^equipment/permissions/(\d+)/$','equipments.views.permissions'),
url(r'^equipment/associations/(\d+)/$','equipments.views.associations'),
url(r'^equipment/finish/$','equipments.views.finish'),
url(r'^equipment/associations/finish/$','equipments.views.assoc_finish'),
url(r'^equipment/fieldnames/(\d+)/$','equipments.views.set_names'),

url(r'^rastreamento/veicular/$', 'rastreamento.views.index'),
url(r'^rastreamento/portatil/$', 'rastreamento.views.index'),
url(r'^rastreamento/loadData/$', 'rastreamento.views.loadData'),
url(r'^rastreamento/xhrtest/$', 'rastreamento.views.xhr_test'),



url(r'^accounts/create/(\d+)/$', 'accounts.views.create_user'),
url(r'^accounts/create/finish/$', 'accounts.views.create_finish'),

url(r'^accounts/delete/(\d+)/$','accounts.views.delete'),
url(r'^accounts/ajax/delete/$','accounts.ajax.delete'),
url(r'^accounts/edit/(\d+)/$','accounts.views.edit'),
url(r'^accounts/edit/finish/$','accounts.views.edit_finish'),
url(r'^accounts/edit/finish_firstlogin/$','accounts.views.finish_firstlogin'),



url(r'^vehicles/$', 'vehicles.views.index'),
url(r'^vehicles/create/(\d+)/$','vehicles.views.create'),
url(r'^vehicles/create/finish/$','vehicles.views.create_finish'),
url(r'^vehicles/edit/(\d+)/$','vehicles.views.edit'),
url(r'^vehicles/edit/finish/$','vehicles.views.edit_finish'),
url(r'^vehicles/delete/(\d+)/$','vehicles.views.delete'),
url(r'^vehicles/delete/finish/$','vehicles.views.delete_finish'),
url(r'^vehicles/swap/(\d+)/$','vehicles.views.swap'),
url(r'^vehicles/swap/finish/$','vehicles.views.swap_finish'),
url(r'vehicles/edit_equip/(\d+)/$','vehicles.ajax.edit_equipment'),
url(r'vehicles/delete_equip/$','vehicles.ajax.delete_equipment'),

url(r'^commands/$', 'command.views.index'),
# url(r'^commands/test/$', 'command.views.test277'), # used to test MaxTrack MTC 400 State
url(r'^commands/test/$', 'command.views.test278'), # used to test Quanta Tetrus State
url(r'^commands/create/(\d+)/$','command.views.create'),
url(r'^commands/load/$','command.ajax.load'),
url(r'^commands/check/$','command.ajax.check'),
url(r'^commands/create/(\d+)/(\d+)/$','command.views.create'),
url(r'^commands/create/finish/$','command.views.create_finish'),
url(r'^commands/delete/(\d+)/$','command.views.delete'),
url(r'^commands/delete/finish/$','command.views.delete_finish'),
url(r'^commands/loadavailable/$','command.views.loadavailable'),

url(r'^drivers/$', 'drivers.views.index'),
url(r'^drivers/create/$','drivers.views.create'),
url(r'^drivers/create/finish/$','drivers.views.create_finish'),
url(r'^drivers/edit/(\d+)/$','drivers.views.edit'),
url(r'^drivers/edit/finish/$','drivers.views.edit_finish'),
url(r'^drivers/delete/(\d+)/$','drivers.views.delete'),
url(r'^drivers/delete/finish/$','drivers.views.delete_finish'),
url(r'^drivers/profile/(\d+)/$','drivers.views.profile'),

url(r'^alerts/$', 'alerts.views.index'),
url(r'^alerts/create/(\d+)/$','alerts.views.create'),
url(r'^alerts/create/finish/$','alerts.views.create_finish'),
url(r'^alerts/edit/(\d+)/$','alerts.views.edit'),
url(r'^alerts/edit/finish/$','alerts.views.edit_finish'),
url(r'^alerts/delete/(\d+)/$','alerts.views.delete'),
url(r'^alerts/delete/finish/$','alerts.views.delete_finish'),
url(r'^alerts/status/$','alerts.ajax.status'),
url(r'^alerts/load/$','alerts.ajax.load'),

url(r'^geofence/$','geofence.views.index'),
url(r'^geofence/create/$','geofence.views.create'),
url(r'^geofence/create2/(\d+)/(\d+)/$','geofence.views.create2'),
#url(r'^geofence/create/$','geofence.views.create'),
url(r'^geofence/create/finish/$','geofence.views.create_finish'),
url(r'^geofence/geocode/$','geofence.ajax.geocoder'),
url(r'^geofence/route/$','geofence.ajax.route_calculator'),
url(r'^geofence/save/$','geofence.views.saveGeofencev2'),
url(r'^geofence/load/$','geofence.views.loadGeofences'),
url(r'^geofence/edit/(\d+)/$','geofence.views.edit'),
url(r'^geofence/edit2/(\d+)/(\d+)/(\d+)/$','geofence.views.edit2'),
url(r'^geofence/edit/finish/$','geofence.views.edit_finish'),
url(r'^geofence/delete/(\d+)/$','geofence.views.delete'),
url(r'^geofence/delete/finish/$','geofence.views.delete_finish'),

url(r'^paths/$','paths.views.index'),
url(r'^paths/load/$','paths.ajax.load'),

url(r'maplink/$','main.views.multispectral'),
url(r'openlayers/$','main.views.openlayers'),

url(r'reports/(\d+)/$','reports.views.report'),
url(r'^reports/checkready','reports.views.checkready'),


(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),


)

alerts/models.py
# -*- coding:utf8 -*-

from django.db import models
from itrack.equipments.models import  Equipment, CustomFieldName
from itrack.geofence.models import Geofence
from django.contrib.auth.models import User
from itrack.system.models import System
from itrack.vehicles.models import Vehicle
from django.utils.encoding import smart_str


class Alert(models.Model):
    name = models.CharField(max_length=200,verbose_name = 'Nome do monitoramento')
    vehicle = models.ManyToManyField(Vehicle,verbose_name = u'Veículo')
    system = models.ForeignKey(System)
    destinataries = models.ManyToManyField(User,verbose_name='Notificados',related_name='alert_destinataries')
    time_start = models.DateTimeField(verbose_name=u'Início do monitoramento')
    time_end = models.DateTimeField(verbose_name='Fim do monitoramento')
    receive_email = models.BooleanField(verbose_name = 'Receber alerta por email')
    receive_sms = models.BooleanField(verbose_name = 'Receber alerta por SMS')
    alerttext = models.CharField(max_length=160,verbose_name = 'Texto a ser enviado por SMS/Email',null=True,blank=True)
    receive_popup = models.BooleanField(verbose_name = u'Exibir popups na tela do usuário logado')
    trigger = models.ForeignKey(CustomFieldName,verbose_name="Evento",null=True)
    
    state = models.BooleanField(verbose_name = 'Alertar quando', choices=((True,"Ligado"),(False,"Desligado"),))
    geofence = models.ForeignKey(Geofence, verbose_name = u"Cerca Eletrônica",null = True,blank = True)
    linear_limit = models.DecimalField(max_digits=8, decimal_places=0,verbose_name = 'Limite')
    linear_limit.null = True
    linear_limit.blank = True
    active = models.BooleanField(verbose_name = 'Ativo')
    sender = models.ForeignKey(User,blank=True,null=True)

    def __unicode__(self):
        return self.name
        
class Popup(models.Model):
    alert = models.ForeignKey(Alert)
    user = models.ForeignKey(User)
    #system = models.ForeignKey(System)
    vehicle = models.ForeignKey(Vehicle)
    date = models.DateTimeField(null = True)
    def __unicode__(self):
        return str(self.alert)+" : "+str(self.vehicle)

paths/models.py
from django.db import models

# Create your models here.

paths/forms.py
# -*- coding: utf-8 -*-
from django.forms import *
from django.db.models import Q
from django.contrib.admin.widgets import *

from itrack.equipments.models import CustomFieldName
from itrack.system.models import System
from itrack.vehicles.models import Vehicle
from itrack.geofence.models import Geofence


VEHICLE_CHOICES = (("license_plate","Placa"),("date","Data"),("type","Tipo de veículo"),("address","Endereço"),("system","Sistema"),("color","Cor"),("year","Ano"),("model","Modelo"),("manufacturer","Fabricante"),("chassi","Chassi"))

class PathForm(Form):
    vehicle = ChoiceField(label=u"Veículo",widget=Select(attrs={'class':'switcher','style':'width: 178px;position:relative;height:25px;',}))
    period_start = DateTimeField(widget=DateTimeInput(attrs={'class':'datepicker','style':'width: 175px;position:relative;'}),label=u"Data inicial")
    period_end = DateTimeField(widget=DateTimeInput(attrs={'class':'datepicker','style':'width: 175px;position:relative;'}),label=u"Data final")
    geofence = ModelChoiceField(Geofence.objects.all(),label=u'Cerca eletrônica',widget=Select(attrs={'style':'width: 178px;position:relative;height:25px;'}),required=False)
    
    
    
    def __init__(self, system, *args, **kwargs):
        super(PathForm, self).__init__(*args, **kwargs)
        #self.fields['vehicle'].queryset = Vehicle.objects.filter(system=system)
        self.fields['geofence'].queryset = Geofence.objects.filter(system=system)
        
        choices = [(v.id, unicode(v)) for v in Vehicle.objects.filter(Q(equipment__system=system)&Q(erased=False))]
        choices.extend([("-1","Outro:")])
        
        try:
            if args[0].has_key('vehicle_other'):
                try:
                    v_oth = Vehicle.objects.get(pk=int(args[0]['vehicle']))
                    choices.extend([(v_oth.id,unicode(v_oth))])
                except ObjectDoesNotExist:
                    pass
        except IndexError:
            pass

        self.fields['vehicle'].choices = choices

paths/views.py
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required, user_passes_test
from querystring_parser import parser
from django.http import HttpResponse
from django.utils import simplejson
from django.contrib.gis import geos

from itrack.system.models import System,Settings
from itrack.equipments.models import CustomField,Equipment,Tracking,TrackingData,EquipmentType
from itrack.geofence.models import Geofence
from itrack.alerts.models import Alert
from itrack.paths.forms import PathForm

def index(request):
    form = PathForm(request.session["system"])
    return render_to_response("paths/templates/home.html",locals())

paths/templates/home.html
{% extends "templates/base.html" %}

{% block head %}

<style type="text/css">

    #id_vehicle{
        width:178px;
    }
    .field {
        height:30px;
    }
    .field #id_vehicle_other{
        margin:0;
    }

    
</style>

<script type="text/javascript" src="http://openlayers.org/api/OpenLayers.js"></script>

<script type="text/javascript" src="/media/js/paths.js"></script>
<script type="text/javascript" src="/media/js/wms.js"></script>
<script type="text/javascript" src="/media/js/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript" src="/media/js/ajaxsend.js"></script>
<script type="text/javascript" src="/media/js/alertcheck.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">
//limiting the maximum and minimum dates
    $(document).ready(function(){
    	
    	 // CONFIGURAÇÃO DO DATEPICKER DO JQUERYUI PARA PT-BR
		$.datepicker.setDefaults({dateFormat: 'dd/mm/yy',
	        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
	        dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
	        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
	        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro', 'Outubro','Novembro','Dezembro'],
	        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set', 'Out','Nov','Dez'],
	        nextText: 'Próximo',
	    	prevText: 'Anterior'
	    });    
	        
        //"Выберите время" russianisk ?? why?
	    $.timepicker.setDefaults({
			timeOnlyTitle: 'Selecione um horario',
			timeText: 'Horário',
			hourText: 'Hora',
			minuteText: 'Minuto',
			secondText: 'Segundo',
			currentText: 'Hora atual',
			closeText: 'Ok',
			ampm: false
		});
	    	
        dates = $( "#id_period_end, #id_period_start " ).datetimepicker({
			    showSecond: true,
                timeFormat: 'hh:mm:ss',
                dateFormat: 'yy-mm-dd',
			    onSelect: function( selectedDate ) {
				    var option = this.id == "id_period_start" ? "minDate" : "maxDate",
					    instance = $( this ).data( "datepicker" ),
					    date = $.datepicker.parseDate(
						    instance.settings.dateFormat ||
						    $.datepicker._defaults.dateFormat,
						    selectedDate, instance.settings );
				
				    date2  = new Date(date);
				    date2.setMonth(date.getMonth()+ (this.id == "id_period_start" ? 1 : -1));
                    
				    var option2 = this.id == "id_period_start" ? "maxDate" : "minDate";				    
					
				    dates.not( this ).datetimepicker( "option", option, date );
				    dates.not( this ).datetimepicker( "option", option2, date2);
			    }
	    });
	    
	    
	    if ($('.switcher option:selected').text() == 'Outro:'){
            this.id = 'id_vehicle_other';
            $(this).attr('name','vehicle_other');
            $(this).parent().append("<input type=\"text\" placeholder=\"Digite a placa\" id=\"id_vehicle\" class=\"vehiclass\" name=\"vehicle\" >");
        }else if(this.id == 'id_vehicle_other'){
            $('#id_vehicle').remove()
            this.id = 'id_vehicle';
            $(this).attr('name','vehicle');
        }
    
    
        $('.switcher').change(function(){
            if ($('.switcher option:selected').text() == 'Outro:'){
                this.id = 'id_vehicle_other';
                $(this).attr('name','vehicle_other');
                $(this).parent().append("<input type=\"text\" placeholder=\"Digite a placa\" id=\"id_vehicle\" class=\"vehiclass\" name=\"vehicle\" >");
            }else if(this.id == 'id_vehicle_other'){
                $('#id_vehicle').remove()
                this.id = 'id_vehicle';
                $(this).attr('name','vehicle');
            } 
        });
	    
	});
</script>
{% endblock %}

{% block content %}
<div  class="main-form" id="geofencetool" style="overflow:hidden;">
    <h1><img class="icon" src="/media/img/command.png">Trajetos </h1><hr/>
<h2>Consultar Trajeto</h2>
<em></em>
    <div style="float:left;width:190px;height:100%;">
        <form style="margin:0;">
            <fieldset style="border: 1px solid #999; width:190px; padding:5px;">
            <legend style="font-weight:bold;">Trajeto</legend>
                <p>{{form.vehicle.label}}:</p><p>{{form.vehicle}}</p>
                <p>{{form.period_start.label}}:</p><p>{{form.period_start}}</p>
                <p>{{form.period_end.label}}:</p><p>{{form.period_end}}</p>
                <p>{{form.geofence.label}}:</p><p>{{form.geofence}}</p>
                <div style="text-align:center;margin:10px;"><a href="#" id="send" class="table-button" style="margin: 5px; padding:5px;">Buscar</a></div>
            </fieldset>
        </form>
        

        <!-- <fieldset style="border: 1px solid #999; width:190px; padding:5px;">
            <legend style="font-weight:bold;">Posição do cursor</legend>
            <p><span style="text-align:right;">Latitude:</span><input id="lat" type="text" style="width: 118px;position:relative;left:14px;"></input></p>
            <p><span style="text-align:right;">Longitude:</span><input id="lng" type="text" style="margin: 5px 0 5px 4px;width: 118px;"></input></p>
        </fieldset> -->

        
    </div>
    
    <div id="distance_float_panel"></div>
    <div id="map" style="float:right;height:555px;width:76%;background-color:white;margin-top:10px;"></div>
   </div>
  
  </div>

   
{% endblock %}