urls.py
from django.shortcuts import render_to_response
from django.conf.urls.defaults import *
from django.contrib.auth.views import login,logout,logout_then_login,password_reset,password_reset_done,password_reset_complete,password_reset_confirm
from django.conf import settings
from itrack.system.forms import UserCompleteForm, SettingsForm, SystemForm, SystemWizard

from django.contrib.gis import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

urlpatterns = patterns('',
url(r'^$', 'main.views.index'),
url(r'^accounts/login/$', 'accounts.views.login' ),
url(r'^accounts/logout/$', logout_then_login),
url(r'^accounts/$', 'accounts.views.index'),
url(r'^accounts/password/reset/$', password_reset, {'template_name': 'accounts/templates/password_reset_form.html','email_template_name': 'accounts/templates/password_reset_email.html','post_reset_redirect' : '/accounts/password/reset/done/'}),
url(r'^accounts/password/reset/done/$', password_reset_done, {'template_name': 'accounts/templates/password_reset_done.html'}),
url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/templates/password_reset_confirm.html','post_reset_redirect' : '/accounts/password/done/'}), 
url(r'^accounts/password/done/$',password_reset_complete, {'template_name': 'accounts/templates/password_reset_complete.html'}),

url(r'^admin/', include(admin.site.urls)),
url(r'^media/(.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),
url(r'^accounts/profile/$', 'main.views.index'),
url(r'^themes/$', 'themes.views.index'),

url(r'^images/(.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),

url(r'^system/$','system.views.index'),
url(r'^system/create/$','system.views.create'),
url(r'^system/edit/(\d+)/$','system.views.edit'),
url(r'^system/delete/(\d+)/$','system.views.delete'),
url(r'^system/finish/$','system.views.finish'),
url(r'^system/edit/finish/$','system.views.editfinish'),
url(r'^system/delete/finish/$','system.views.deletefinish'),
url(r'^sys_not_created/$','system.views.sys_not_created'),
url(r'^system/sms_count/$','system.ajax.get_sms_count'),


url(r'^equipment/$','equipments.views.index'),
url(r'^equipment/permissions/(\d+)/$','equipments.views.permissions'),
url(r'^equipment/associations/(\d+)/$','equipments.views.associations'),
url(r'^equipment/finish/$','equipments.views.finish'),
url(r'^equipment/associations/finish/$','equipments.views.assoc_finish'),
url(r'^equipment/fieldnames/(\d+)/$','equipments.views.set_names'),

url(r'^rastreamento/veicular/$', 'rastreamento.views.index'),
url(r'^rastreamento/portatil/$', 'rastreamento.views.index'),
url(r'^rastreamento/loadData/$', 'rastreamento.views.loadData'),
url(r'^rastreamento/xhrtest/$', 'rastreamento.views.xhr_test'),



url(r'^accounts/create/(\d+)/$', 'accounts.views.create_user'),
url(r'^accounts/create/finish/$', 'accounts.views.create_finish'),

url(r'^accounts/delete/(\d+)/$','accounts.views.delete'),
url(r'^accounts/ajax/delete/$','accounts.ajax.delete'),
url(r'^accounts/edit/(\d+)/$','accounts.views.edit'),
url(r'^accounts/edit/finish/$','accounts.views.edit_finish'),
url(r'^accounts/edit/finish_firstlogin/$','accounts.views.finish_firstlogin'),



url(r'^vehicles/$', 'vehicles.views.index'),
url(r'^vehicles/create/(\d+)/$','vehicles.views.create'),
url(r'^vehicles/create/finish/$','vehicles.views.create_finish'),
url(r'^vehicles/edit/(\d+)/$','vehicles.views.edit'),
url(r'^vehicles/edit/finish/$','vehicles.views.edit_finish'),
url(r'^vehicles/delete/(\d+)/$','vehicles.views.delete'),
url(r'^vehicles/delete/finish/$','vehicles.views.delete_finish'),
url(r'^vehicles/swap/(\d+)/$','vehicles.views.swap'),
url(r'^vehicles/swap/finish/$','vehicles.views.swap_finish'),
url(r'vehicles/edit_equip/(\d+)/$','vehicles.ajax.edit_equipment'),
url(r'vehicles/delete_equip/$','vehicles.ajax.delete_equipment'),

url(r'^commands/$', 'command.views.index'),
# url(r'^commands/test/$', 'command.views.test277'), # used to test MaxTrack MTC 400 State
url(r'^commands/test/$', 'command.views.test278'), # used to test Quanta Tetrus State
url(r'^commands/create/(\d+)/$','command.views.create'),
url(r'^commands/load/$','command.ajax.load'),
url(r'^commands/check/$','command.ajax.check'),
url(r'^commands/create/(\d+)/(\d+)/$','command.views.create'),
url(r'^commands/create/finish/$','command.views.create_finish'),
url(r'^commands/delete/(\d+)/$','command.views.delete'),
url(r'^commands/delete/finish/$','command.views.delete_finish'),
url(r'^commands/loadavailable/$','command.views.loadavailable'),

url(r'^drivers/$', 'drivers.views.index'),
url(r'^drivers/create/$','drivers.views.create'),
url(r'^drivers/create/finish/$','drivers.views.create_finish'),
url(r'^drivers/edit/(\d+)/$','drivers.views.edit'),
url(r'^drivers/edit/finish/$','drivers.views.edit_finish'),
url(r'^drivers/delete/(\d+)/$','drivers.views.delete'),
url(r'^drivers/delete/finish/$','drivers.views.delete_finish'),
url(r'^drivers/profile/(\d+)/$','drivers.views.profile'),

url(r'^alerts/$', 'alerts.views.index'),
url(r'^alerts/create/(\d+)/$','alerts.views.create'),
url(r'^alerts/create/finish/$','alerts.views.create_finish'),
url(r'^alerts/edit/(\d+)/$','alerts.views.edit'),
url(r'^alerts/edit/finish/$','alerts.views.edit_finish'),
url(r'^alerts/delete/(\d+)/$','alerts.views.delete'),
url(r'^alerts/delete/finish/$','alerts.views.delete_finish'),
url(r'^alerts/status/$','alerts.ajax.status'),
url(r'^alerts/load/$','alerts.ajax.load'),

url(r'^geofence/$','geofence.views.index'),
url(r'^geofence/create/$','geofence.views.create'),
url(r'^geofence/create2/(\d+)/(\d+)/$','geofence.views.create2'),
#url(r'^geofence/create/$','geofence.views.create'),
url(r'^geofence/create/finish/$','geofence.views.create_finish'),
url(r'^geofence/geocode/$','geofence.ajax.geocoder'),
url(r'^geofence/route/$','geofence.ajax.route_calculator'),
url(r'^geofence/save/$','geofence.views.saveGeofencev2'),
url(r'^geofence/load/$','geofence.views.loadGeofences'),
url(r'^geofence/edit/(\d+)/$','geofence.views.edit'),
url(r'^geofence/edit2/(\d+)/(\d+)/(\d+)/$','geofence.views.edit2'),
url(r'^geofence/edit/finish/$','geofence.views.edit_finish'),
url(r'^geofence/delete/(\d+)/$','geofence.views.delete'),
url(r'^geofence/delete/finish/$','geofence.views.delete_finish'),

url(r'^paths/$','paths.views.index'),
url(r'^paths/load/$','paths.ajax.load'),

url(r'maplink/$','main.views.multispectral'),
url(r'openlayers/$','main.views.openlayers'),

url(r'reports/(\d+)/$','reports.views.report'),
url(r'^reports/checkready','reports.views.checkready'),


(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),


)

command/models.py
# -*- coding: utf8 -*-

from django.db import models
from itrack.equipments.models import  Equipment, CustomFieldName
from itrack.vehicles.models import Vehicle
from django.contrib.auth.models import User
from itrack.system.models import System
from django.db.models import Max

STATE_CHOICES = ((u'0',"Enviado para o servidor"),(u'1',"Transmitindo para o equipamento"),(u'2',"Comando executado"),(u'3',"Falha no envio"))
ACTION_CHOICES = (("ON","Ativar"),("OFF","Desativar"),)

class Command(models.Model):

    equipment = models.ForeignKey(Vehicle,verbose_name=u"Veículo")
    system = models.ForeignKey(System)
    type = models.ForeignKey(CustomFieldName,verbose_name="Comando",null=True)
    state = models.CharField(max_length=50, choices = STATE_CHOICES)
    action = models.CharField(max_length=10, choices = ACTION_CHOICES,verbose_name= u"Ação",default='ON')
    time_sent = models.DateTimeField('data enviada',blank=True,null=True)
    time_received = models.DateTimeField('data recebida',blank=True,null=True)
    time_executed = models.DateTimeField('data executada',blank=True,null=True)
    sender = models.ForeignKey(User,blank=True,null=True)
    
    def __unicode__(self):
        return self.equipment.license_plate
        
class CPRSession(models.Model):
    key = models.CharField(max_length=50)
    time = models.DateTimeField('timestamp')

command/forms.py
# -*- coding: utf8 -*-
from itrack.command.models import Command
from django.forms import *
from django import forms


class CommandForm(ModelForm):
    class Meta:
        model = Command
        exclude = ['time_sent','time_executed','time_received','system','state','sender']
        widgets = {
            'action': RadioSelect(attrs={'disabled':'disabled'})
        }
    
    username = CharField(label="Usuário")
    password = forms.CharField(label="Senha",widget=forms.PasswordInput(render_value=True),)

#    activate = ChoiceField(choices = (("ON","Ativar"),("OFF","Desativar"),),widget=RadioSelect(),label=u"Ação")
        

command/templates/create.html
{% extends "command/templates/form.html" %}

{%block title%}Infotrack - Envio de comando {% endblock %}
{% block form_title %}
<h1><img class="icon" src="/media/img/command.png">Envio de comando </h1><hr/>
<h2>Dados do comando</h2>
<em></em>
{% endblock %}


{% block content %}
{% if not vehicles_exist %}
<div  class="main-form">
<h1><img class="icon" src="/media/img/command.png">Envio de comando </h1><hr/>
<h2>Dados do comando</h2>
<em>O Cliente não possui nenhum veículo associado aos equipamentos. É necessário associar os veículos aos equipamentos antes de enviar comandos. <a href = "{% url vehicles.views.index %}"> Clique aqui para ir a tela de administração de veículos. </a></em>


</div>
{% else %}
   {{ block.super }}
{% endif %}
{% endblock %}

command/templates/create_finish.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Envio de comando {% endblock %}
{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/command.png">Envio de comando</h1>
<hr />
<h2> Comando criado com sucesso </h2>
<em>O comando foi criado com sucesso. <a href="{% url command.views.index %}"> Clique aqui para voltar a tela de histórico de comandos. </a></em>

</div>
{% endblock %}

command/templates/delete.html
{% extends "templates/base.html" %}
{%  block title %}Infotrack - Remoção de comando{% endblock  %}
{% block content  %}

<div class="main-form">
  <h1><img class="icon" src="/media/img/command.png">Histórico de comandos</h1>
  <hr />
					<h2>Remoção de Comando</h2>
					<em> Tem certeza que deseja remover o comando "{{ c.type }}" do veículo "{{ c.equipment.license_plate }}"? </em>
					
					<div align="center" style="margin-top:10px;" id="actions">
            
            <form action='.' method='post'>{% csrf_token %}
                <a href="#" onClick="parentNode.submit();">Confirmar</a>
                <a onClick="history.back();">Cancelar</a>
            </form>
            </div>

{% endblock %}

command/templates/delete_finish.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Remoção de Comando {% endblock %}

{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/command.png">Remoção de Comando</h1>
<hr />
<h2> Remoção finalizada com sucesso </h2>
<em>O Comando foi removido do sistema. <a href="{% url command.views.index %}"> Clique aqui para voltar a tela de Histórico de Comandos. </a></em>

</div>
{% endblock %}

command/templates/edit.html
{% extends "accounts/templates/form.html" %}

{%block title%}Infotrack -Edição de Veículo {% endblock %}
{% block form_title %}
<h1><img class="icon" src="/media/img/command.png">Criação de veículo </h1>
<h2>Dados de cadastro</h2>
<em>Informe os dados necessários para o cadastro do veículo no sistema.</em>
{% endblock %}

command/templates/edit_finish.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Edição de Veículo {% endblock %}
{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/command.png">Edição de Veículo</h1>
<hr />
<h2> Edição finalizada com sucesso </h2>
<em>O veículo foi editado com sucesso. <a href="{% url vehicles.views.index %}"> Clique aqui para voltar a tela de administração de veículos. </a></em>

</div>
{% endblock %}

command/templates/error.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Envio de comando {% endblock %}
{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/command.png">Envio de comando</h1>
<hr />
<h2>{{error_title}} </h2>
<em>{{error}} <a href="{% url command.views.index %}"> Clique aqui para voltar a tela de histórico de comandos. </a></em>

</div>
{% endblock %}

command/templates/error2.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Envio de comando {% endblock %}
{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/command.png">Envio de comando</h1>
<hr />
<h2> Erro: Já existe um comando sendo processado para este veículo </h2>
<em>O comando a ser enviado selecionou um veículo com um comando já existente. Por favor, exclua qualquer comando relacionado ao veículo selecionado antes de enviar outro comando. <a href="{% url command.views.index %}"> Clique aqui para voltar a tela de histórico de comandos. </a></em>

</div>
{% endblock %}

command/templates/form.html
{% extends "templates/base.html" %}

{% block head %}
<script type="text/javascript" src="/media/js/command.js"></script>


<script>

function xml_to_string(xml_node)
{
    if (xml_node.xml)
        return xml_node.xml;
    else if (XMLSerializer)
    {
        var xml_serializer = new XMLSerializer();
        return xml_serializer.serializeToString(xml_node);
    }
    else
    {
        alert("ERROR: Extremely old browser");
        return "";
    }
}
jQuery(document).ready(function(){ 

    var obj = document.getElementById("id_equipment");
    obj.onchange = function() {
        //alert(obj.value);
        $.ajax({
            url: "/commands/loadavailable?id=" + obj.value,
            context : document.body,
            dataType : "xml",
            success: function(xmlNode) {
//                alert(xmlNode)
  //              alert(xml_to_string(xmlNode))
//                alert("START");
                root = xmlNode.childNodes[0];    
                x=root.childNodes;
                msg = ""
                var values = [];
                var test = true;
                var c = 0;
                var msg = "";
                for (i=0;i<x.length;i++)
                {
                    //selected="selected" 
                    if(x[i].nodeName=="field") {
                        if(x[i].childNodes.length==2) {
                            var k1 = "";
                            var v1 = "";
                            if(x[i].childNodes[0].nodeName=="key") {
                                k1 = x[i].childNodes[0].childNodes[0].nodeValue;
                            } 
                            if(x[i].childNodes[1].nodeName=="val") {
                                v1 = x[i].childNodes[1].childNodes[0].nodeValue;
                            } 
                            msg += k1 + " :: " + v1 + "\n"
                            values.push([k1,v1]);
                        }
                    }
                    if(x[i].nodeName=="msg") {
                        msg = x[i].childNodes[0].nodeValue;
                    }
    //                $('#mySelect').empty().append('<option selected="selected" value="whatever">text</option>');
//                    alert("Nodename: " + x[i].nodeValue);
  //                  alert(" nodetype: " + x[i].nodeType    );
                }
//                if(msg!= undefined && msg!="") alert(msg);
                jQuery('#id_type').empty();
                for(i=0;i<values.length;i++) {
                    jQuery('#id_type').append('<option value="'+values[i][0]+'">'+values[i][1]+'</option>');
                }
//                alert("DONE");
            }
        });
    }
    
 });

</script>

{% endblock %}


{% block content %}
<div  class="main-form">
{% block form_title %}
<h1><img class="icon" src="/media/img/command.png">Criação de usuário </h1>
<hr />
<h2>Dados de cadastro</h2>
<em>Informe os dados necessários para o cadastro do usuário no sistema.</em>
{% endblock %}
<form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
      <table>
    {% for field in form %}
        <tr>
        <td>
        <div class="form-item">
            <div class="item-left">          
                  <p>{{ field.label_tag }} {%if field.field.required%} *{%endif%}</p>
                  <p id="help">{{ field.help_text|wordwrap:"50"|linebreaksbr }} </p>
            </div>
        </td>
        <td>
            <div class="item-right">
                <p class="errorlist">{{ field.errors }} </p>
                 <p class="field">{{ field }} </p>          
            </div>
        </div>
        </td>
        </tr>
    {% endfor %}
    </table>
<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
<input type="submit" value="Prosseguir" class="submit">
<p class="clear">
</form>

</div>
{% endblock %}

command/templates/swap.html
{% extends "accounts/templates/form.html" %}

{%block title%}Infotrack -Edição de Veículo {% endblock %}
{% block form_title %}
<h1><img class="icon" src="/media/img/command.png">Criação de veículo </h1>
<h2>Dados de cadastro</h2>
<em>Informe os dados necessários para o cadastro do veículo no sistema.</em>
{% endblock %}

command/templates/test277.html
{% extends "templates/base.html" %}
{%block title%}Infotrack - Histórico de comandos {% endblock %}
{% block head %}


{% endblock  %}



{% block content %}

{{output1}}

{% block dialog %}

{% endblock %}


{% csrf_token %}



{% endblock %}